### ISSUE TITLE
Feature Request: Pause resumes to Live broadcast

### ISSUE THREAD

**Issue by awooganl** [expectingtofly/LMS_BBC_Sounds_Plugin#138]
Hi, first off, thank you for this brilliant plug-in.  I never knew this existed until the BBC starting to broadcast their warning messages at regular intervals on my bookmarked stream, but I'm glad I found it.

I use it exclusively to listen to live radio (bbc radio 1) whilst I'm at work and noticed that every time I had to mute the broadcast by using the pause button (for instance, when a work's team call comes in), I then had to use the double skip forward button to resume again at the live broadcast.  If I only press pause again it would resume the broadcast, but now 'delayed'.  Was very confusion to hear the news announcement at a different time :)

Would it be possible to have a setting that allows you to uses the pause as a stop/start instead of pause/unpause?

**Comment by expectingtofly** [comment]
Unfortunately, the plugin is just responding to the command that LMS sends it.  So it pauses when it receives a pause and stops when it receives a stop.  So it would be confusing for the plugin to have an option to do something else.  Some controllers have a separate stop button some only have pause.
What are you using to listen, is it a logitech squeezebox radio?  That doesn't have a separate stop button(although a long press of the pause button stops I think IIRC)
If you are listening on the radio there are a couple of options.  If you just want to mute, why not just press the mute button (the volume button)?  
OR, if you do want to stop the stream, you could press the power button.  Pressing the power button to come on again will mean the stream restarts, but you will need to makes sure you have the right setting in LMS to make sure it restarts rather than unpauses : (stop at power off/Restart at power on is the right setting I believe)

![image](https://user-images.githubusercontent.com/73394021/211759281-3e7db31d-d582-47d4-923e-7717e517c46c.png)

**Comment by awooganl** [comment]
It's a Duet.  The remote does not have any of those buttons available.  The volume buttons reduce/increase the volume.  The pause operates as the pause and pressing it long makes no difference (just tried).  The power button works on the remote, not the receiver.

I did try the player settings, but that only works if the receiver is powered off, and as that is permanently on, that doesn't apply either.

**Comment by expectingtofly** [comment]
Ah right,  have you tried any of the controllers available?  There are plenty to try, all of which do what you want (have a mute, stop or power)  Material, Squeezer, ipeng, Squeeze controle, orange squeeze?

**Comment by awooganl** [comment]
No, not tried other controllers, and feel that that is not really a workable thing for me anyway.

I'll manage with the current option available of double forwarding.  Thanks for the insight and help.
