### ISSUE TITLE
Feature Request: user customization of Stations & schedules listing...

### ISSUE THREAD

**Issue by Rich28** [expectingtofly/LMS_BBC_Sounds_Plugin#145]
Huge thanks for developing this fab plugin.  This is perhaps a minor thing, but I was just wondering if the Stations & schedules listing could be customised in the plugin settings so as to comprise just some the radio stations that are broadcast (rather than the full listing which it currently features)

**Comment by expectingtofly** [comment]
Unfortunatley, I need to be able to leave the Stations & Schedules list complete.    What I could do, is a facility to be able to add a whole stations menu to favourites so that you can put the station & schedules for the stations you like in your own favourites folder in LMS.  I'll add that to the list

**Comment by Rich28** [comment]
- that's a good way forward, which will be really appreciated, thanks
