### ISSUE TITLE
Playback pitch-shifted down on (original) Squeezebox

### ISSUE THREAD

**Issue by gloomytrousers** [expectingtofly/LMS_BBC_Sounds_Plugin#75]
I have a Squeezebox and live radio (I've tried Radio 2 and 6 Music, nothing else so far) is pitch-shifted down, so everything sounds deeper than it should be. It's not unintelligible but is definitely noticeable.

The "Hide the audio sample rate from LMS" setting makes no difference. This is the 320kbps CBR streams. These sound OK on Squeezelite on my PC and on my Boom (although I have frequent rebuffering on the latter - possibly a new issue to follow once I've tried a few things).

The server is logitechmediaserver-8.1.1-1.noarch (just upgraded; I got the same on on logitechmediaserver-8.0.1-0.1.1606059084.noarch) and v2.14.2 of BBC Sounds plugin.

Any assistance or suggestions appreciated for how I can fix this!

**Comment by expectingtofly** [comment]
Hi
The plugin serves streams in the format AAC at 320 kbps with a sample rate of 48000 hz.   If your player cannot support AAC (or the sample rate) then your LMS server will transcode it for the player.   Neither the original squeezebox or the boom support AAC so your LMS will be transcoding for those.  
The best settings on your server is to make sure that it transcodes to FLAC.  So in settings-advanced->file types  your settings should look something like this : 
![image](https://user-images.githubusercontent.com/73394021/110594972-5f99be00-8175-11eb-8e37-61af58709eb5.png)

I have little knowledge of the original squeezebox but I suspect it doesn't support FLAC, so your server is probably transcoding to PCM.  PCM doesn't include timing information, I don't believe, so that is why you are hearing the pitch problem for the 48000 sample rate.  Check your settings, you may need to get the transcoding working for AAC to MP3 for it to sound reasonable on your original squeezebox.

To be honest, this isn't a problem with the BBC sounds plugin in particular, so if you post hear, you are only going to get help from me.  Your best bet is to post on the BBC Sounds thread on the forum to get wider community help : https://forums.slimdevices.com/showthread.php?113045-Announce-BBC-Sounds-Plugin

**Comment by gloomytrousers** [comment]
Thanks, setting "PCM" to "Disabled" in that screen does the trick (MP3 and FLAC are both enabled).
