### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by gallafent** [expectingtofly/LMS_BBC_Sounds_Plugin#93]
I haven't investigated much yet, but it appears that after some time the memory allocation footprint of my squeezeboxserver process (running on a Raspberry Pi, Raspbian Jessie) has grown to a sufficient size that it is no longer possible to start playing a new stream using this plugin. This server has been running for many years in this configuration without this problem, it has only occurred since I installed the BBC Sounds plugin (and retired the iPlayer plugin). The process size has generally reached about 1GB by this time. At present it's around the 750MB mark. At the moment the _only_ content I'm playing using this system is via BBC Sounds, and almost all of it is the live streams (I am in the UK).

The errors I see when it is no longer able to play a stream look like this:

`[21-08-06 17:18:57.8065] Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Networking::Async::HTTP::_http_read_body: open2: fork failed: Cannot allocate memory at /usr/share/perl5/Slim/Player/Pipeline.pm line 138.
; fh=Slim::Networking::Async::Socket::HTTPS=GLOB(0x19459998)`

… but of course that is not saying anything about the cause of the memory growth.

I don't have perl debugging expertise, but if there's a way to attach a memory monitor to the squeezeboxserver process to observe allocations (and leaks) in a straightforward way, happy to do that.

**Comment by expectingtofly** [comment]
Thank you for reporting.    I will do some investigation.

The most likely cause is that the plugin supports http/1.1 so that it doesn't need to do the ssl/https negotiation every time it gets a chunk of audio.  But that does mean it keeps the http connection open between calls with the opportunity for memory leaks if things aren't closed down properly.  I must admit I haven't noticed the leak (I also use raspberry pi with picoreplayer) with lots of use every day, but I do have a weekly reboot scheduled which could be masking it .

I wonder how good the http/1.1 implementation is in various versions of LMS, I did have to do various bits of jiggery pokery to get it to work.    Please could you let me know the version of LMS you are using?

**Comment by expectingtofly** [comment]
Also please can you let me know at what rate the memory footprint grows

**Comment by expectingtofly** [comment]
See the discussion here : https://forums.slimdevices.com/showthread.php?113045-Announce-BBC-Sounds-Plugin&p=1050509&viewfull=1#post1050509

This appears to be a problem with a specific version of LMS, upgrade LMS to fix this problem.
